version: "3.3"

services:
  db:
    image:  nouchka/sqlite3:latest
    volumes:
      - ./data/db:/root/db
    environment:
      - SQLITE3_DB=db.sqlite3
  web:
    build: ./
    command: >
      sh -c "python3 manage.py makemigrations  &&
             python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./src:/src
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - ENV=developement
    depends_on:
      - db